# Site settings
title: Workshop on Structured Prediction."
email: your-email@domain.com
description: "Workshop on structured prediction."
baseurl: "/structuredprediction/"
url: "http://harvardnlp.github.io/structuredprediction/"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
